Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,13 +1,13 @@
 name: Build Kernel
 
-于:
+on:
   workflow_dispatch:
     inputs:
       device:
         description: 'Target Device Codename (e.g., lmi, umi)'
         required: true
-        默认: 'alioth'
-        输入: choice
+        default: 'alioth'
+        type: choice
         options:
           - psyche
           - thyme
@@ -26,8 +26,8 @@ name: Build Kernel
       script:
         description: 'Select Build Script'
         required: true
-        默认: 'build-miui.sh'
-        输入: choice
+        default: 'build-miui.sh'
+        type: choice
         options:
           - build.sh
           - build-miui.sh
@@ -44,94 +44,92 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Source
-      uses: actions/checkout@v6
-      with:
-        fetch-depth: 1
+      - name: Checkout Source
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 1
 
-    - name: Cleanup Disk Space
-      run: |
-        sudo rm -rf /usr/share/dotnet
-        sudo rm -rf /opt/ghc
-        sudo rm -rf "/usr/local/share/boost"
-        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Cleanup Disk Space
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-    - name: Install Dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3
 
-    - name: Setup Cache (ccache)
-      uses: actions/cache@v5
-      with:
-        path: ~/.cache/ccache_mikernel
-        key: kernel-ccache-${{ inputs.device }}-${{ inputs.script }}-${{ github.run_id }}
-        restore-keys: |
-          kernel-ccache-${{ inputs.device }}-${{ inputs.script }}-
-          kernel-ccache-${{ inputs.device }}-
-          kernel-ccache-
+      - name: Setup Cache (ccache)
+        uses: actions/cache@v5
+        with:
+          path: ~/.cache/ccache_mikernel
+          key: kernel-ccache-${{ inputs.device }}-${{ inputs.script }}-${{ github.run_id }}
+          restore-keys: |
+            kernel-ccache-${{ inputs.device }}-${{ inputs.script }}-
+            kernel-ccache-${{ inputs.device }}-
+            kernel-ccache-
 
-    - name: Setup Toolchain (ZyC-Clang 16)
-      run: |
-        mkdir -p $HOME/zyc-clang
-        cd $HOME/zyc-clang
-        wget -q https://github.com/ZyCromerZ/Clang/releases/download/16.0.6-20260510-release/Clang-16.0.6-20260510.tar.gz
-        tar -zxvf Clang-16.0.6-20260510.tar.gz
+      - name: Setup Toolchain (ZyC-Clang 16)
+        run: |
+          mkdir -p $HOME/zyc-clang
+          cd $HOME/zyc-clang
+          wget -q https://github.com/ZyCromerZ/Clang/releases/download/16.0.6-20260510-release/Clang-16.0.6-20260510.tar.gz
+          tar -zxvf Clang-16.0.6-20260510.tar.gz
 
-    - name: Build Kernel
-      id: build
-      run: |
-        chmod +x build.sh build-miui.sh
-        
-        echo "Using script: ${{ inputs.script }}"
-        LOG_FILE="build.log"
-        
-        if [ "${{ inputs.ksu }}" == "true" ]; then
-          echo "Building with KernelSU..."
-          bash ${{ inputs.script }} ${{ inputs.device }} ksu | tee $LOG_FILE
-        else
-          echo "Building without KernelSU..."
-          bash ${{ inputs.script }} ${{ inputs.device }} | tee $LOG_FILE
-        fi
+      - name: Build Kernel
+        id: build
+        run: |
+          chmod +x build.sh build-miui.sh
+          echo "Using script: ${{ inputs.script }}"
+          LOG_FILE="build.log"
 
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v6
-      with:
-        name: Kernel-${{ inputs.device }}-${{ inputs.script }}-${{ inputs.ksu && 'KSU' || 'NoKSU' }}-${{ github.run_number }}
-        path: |
-          ./*.zip
-          build.log
-        if-no-files-found: error
+          if [ "${{ inputs.ksu }}" == "true" ]; then
+            echo "Building with KernelSU..."
+            bash ${{ inputs.script }} ${{ inputs.device }} ksu | tee $LOG_FILE
+          else
+            echo "Building without KernelSU..."
+            bash ${{ inputs.script }} ${{ inputs.device }} | tee $LOG_FILE
+          fi
 
-    - name: Send Kernel & Log to Telegram
-      if: success()
-      env:
-        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-      run: |
-        KERNEL_ZIP=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
-        LOG_FILE="build.log"
-        RUN_ID=${{ github.run_id }}
-        REPO_URL="https://github.com/${{ github.repository }}/actions/runs/$RUN_ID"
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v6
+        with:
+          name: Kernel-${{ inputs.device }}-${{ inputs.script }}-${{ inputs.ksu && 'KSU' || 'NoKSU' }}-${{ github.run_number }}
+          path: |
+            ./*.zip
+            build.log
+          if-no-files-found: error
 
-        if [ -z "$KERNEL_ZIP" ]; then
-          echo "❌ Kernel zip not found"
-          exit 1
-        fi
+      - name: Send Kernel & Log to Telegram
+        if: success()
+        env:
+          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+        run: |
+          KERNEL_ZIP=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
+          LOG_FILE="build.log"
+          RUN_ID=${{ github.run_id }}
+          REPO_URL="https://github.com/${{ github.repository }}/actions/runs/$RUN_ID"
 
-        CAPTION="🚀 *Kernel Build Success*
+          if [ -z "$KERNEL_ZIP" ]; then
+            echo "❌ Kernel zip not found"
+            exit 1
+          fi
 
-        📱 *Device:* \`${{ inputs.device }}\`
-        🛠️*Script:* \`${{ inputs.script }}\`
-        🧩 *KernelSU:* \`${{ inputs.ksu && 'Enabled' || 'Disabled' }}\`
-        🔢 *Run:* \`#${{ github.run_number }}\`
+          CAPTION="🚀 *Kernel Build Success*
 
-        📥 *Download:*
-        [Kernel ZIP & Logs]($REPO_URL)"
+          📱 *Device:* \`${{ inputs.device }}\`
+          🛠️ *Script:* \`${{ inputs.script }}\`
+          🧩 *KernelSU:* \`${{ inputs.ksu && 'Enabled' || 'Disabled' }}\`
+          🔢 *Run:* \`#${{ github.run_number }}\`
 
-        # Send Kernel ZIP
-        curl -F chat_id="$CHAT_ID" \
-             -F document=@"$KERNEL_ZIP" \
-             -F caption="$CAPTION" \
-             -F parse_mode="Markdown" \
-             https://api.telegram.org/bot$BOT_TOKEN/sendDocument
+          📥 *Download:*
+          [Kernel ZIP & Logs]($REPO_URL)"
+
+          curl -F chat_id="$CHAT_ID" \
+               -F document=@"$KERNEL_ZIP" \
+               -F caption="$CAPTION" \
+               -F parse_mode="Markdown" \
+               https://api.telegram.org/bot$BOT_TOKEN/sendDocument
